name: send email

# on:
#   schedule:
#     - cron: "0 11 * * *"

on:
  # Trigger the workflow on push or pull request but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAIL_USER: ${{secrets.MAIL_USER}}
      MAIL_PASS: ${{secrets.MAIL_PASS}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and send email
        run: |
          python -m pip install --upgrade pip
          pip install requests, beautifulsoup4
          pip install pipenv
          pipenv install
          pipenv run python scrape.py
